### ISSUE TITLE
Data Gaps and queue stops reporting 

### ISSUE THREAD

**Issue by shubhamnyaik** [newrelic-experimental/nri-as400#4]
[NOTE]: # ( ^^ Provide a general summary of the issue in the title above. ^^ )
After putting the integration in place and updating the config file and definition file, we observe there are gaps in the data received. 
We are running the query in System status event. 

Whenever the as400 restarts over weekend, we observe that messageque event stops reporting data. 
The fix for this mentioned in read as to delete the checkpoint file and restart the agent, but it happens after every server restart. 

## Description

[NOTE]: # Gaps in data for systemstatus event, the graph dips after every 1-2 mins, updated the definition file also. 
[TIP]:  # ( Do NOT give us access or passwords to your New Relic account or API keys! )

## Steps to Reproduce

[NOTE]: # Run the query : Select count(*) from `AS400:SystemStatusEvent` timeseries 

## Expected Behavior

[NOTE]: # Smooth line with no data loss. 

## Relevant Logs / Console output

[NOTE]: # ( Please provide specifics of the local error logs, Browser Dev Tools console, etc. if appropriate and possible. )

## Your Environment

[TIP]:  # ( Include as many relevant details about your environment as possible. )

* ex: Browser name and version:
* ex: Operating System and version:

## Additional context

[TIP]:  # ( Add any other context about the problem here. )

**Comment by RohitSachdeva-MPG** [comment]
Hi @shubhamnyaik @sschwartzman Any solution for the above issue, I am also facing the same where message queue data is coming on intermittent basis. Sometimes it is coming to NR after 2 days when compared the time of message queue events in AS400.

**Comment by gsidhwani-nr** [comment]
Please share the feedback based on latest released version 1.2.0 and we will address the same.
