### ISSUE TITLE
System Status Not Reporting

### ISSUE THREAD

**Issue by cdoc-hcs** [newrelic-experimental/nri-as400#5]
[NOTE]: # ( ^^ Provide a general summary of the issue in the title above. ^^ )

## Description

[NOTE]: # ( Describe the problem you're encountering. )
[TIP]:  # ( Do NOT give us access or passwords to your New Relic account or API keys! )

New Relic infrastructure agent running on linux server stops retrieving data for SystemStatusEvent after a few hours. As of now there is nothing within the NR infrastructure logs to indicate a problems (no errors). The call will consistently execute until it just stops.
We do not have visibility into the code that executes these but here it seems to stop attempting to connect to the client AS400.
 
This issue occurs trying to connect to various client servers. Some more frequently than others.
 
Client server logs does not show any odd activity around the time of last new relic user connection to AS400 for retrieval of status info. Based off of the NR logs, it looks as though the agent stops trying to run command for system status for that given client.
 
Resetting the connection, calling install_linux.sh will resolve the problem but as mentioned before will usually begin failing again after a few hours.

## Steps to Reproduce

[NOTE]: # ( Please be as specific as possible. )
We cannot reproduce on demand but problem occurs multiple times daily.

## Expected Behavior

[NOTE]: # ( Tell us what you expected to happen. )
Continuous data retrieval.

## Relevant Logs / Console output

[NOTE]: # ( Please provide specifics of the local error logs, Browser Dev Tools console, etc. if appropriate and possible. )

## Your Environment

[TIP]:  # ( Include as many relevant details about your environment as possible. )

* ex: Browser name and version:
* ex: Operating System and version:

## Additional context

[TIP]:  # ( Add any other context about the problem here. )

**Comment by gsidhwani-nr** [comment]
Please share the feedback based on latest released version 1.2.0 and we will address the same.
